name: Tests

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Build
        run: bash build.sh

  scenario-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Unit Test
        run: go test -v -gcflags=-l -race -covermode=atomic -coverprofile=coverage.txt ./...
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)

  compatibility-test:
    strategy:
      matrix:
        go: [ 1.18, 1.19.12, 1.20.7 ]
        os: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Unit Test
        run: go test -v -gcflags=-l -race -covermode=atomic ./...
